export const weatherIcons = {
  // iconName: imageURL (use require() to allow processing image via Webpack)
  "clear-day": require("@images/weather-icons/clear-day.svg"),
  "clear-night": require("@images/weather-icons/clear-night.svg"),
  cloudy: require("@images/weather-icons/cloudy.svg"),
  fog: require("@images/weather-icons/fog.svg"),
  hail: require("@images/weather-icons/hail.svg"),
  "partly-cloudy-day": require("@images/weather-icons/partly-cloudy-day.svg"),
  "partly-cloudy-night": require("@images/weather-icons/partly-cloudy-night.svg"),
  "rain-snow-shower-day": require("@images/weather-icons/rain-snow-showers-day.svg"),
  "rain-snow-shower-night": require("@images/weather-icons/rain-snow-showers-night.svg"),
  "rain-snow": require("@images/weather-icons/rain-snow.svg"),
  rain: require("@images/weather-icons/rain.svg"),
  "showers-day": require("@images/weather-icons/showers-day.svg"),
  "showers-night": require("@images/weather-icons/showers-night.svg"),
  sleet: require("@images/weather-icons/sleet.svg"),
  "snow-showers-day": require("@images/weather-icons/snow-showers-day.svg"),
  "snow-showers-night": require("@images/weather-icons/snow-showers-night.svg"),
  snow: require("@images/weather-icons/snow.svg"),
  "thunder-rain": require("@images/weather-icons/thunder-rain.svg"),
  "thunder-showers-day": require("@images/weather-icons/thunder-showers-day.svg"),
  "thunder-showers-night": require("@images/weather-icons/thunder-showers-night.svg"),
  thunder: require("@images/weather-icons/thunder.svg"),
  wind: require("@images/weather-icons/wind.svg"),
};
